### ISSUE TITLE
optional useAnimationFrame()

### ISSUE THREAD

**Issue by KutnerUri** [franciscop/use-animation-frame#2]
requiring animation frame is expensive, as it will run multiple times a second.
(unlike `useEffect()`, which only runs on change)

Therefor, I want a way to disable the hook when not needed, like:

```tsx
useAnimationFrame(() => update(), [update], { enabled: !!update } );

// double negative is generally bad, but I've seen 'skip: true' before:
useAnimationFrame(() => update(), [update], { skip: !update } );
```

**Comment by franciscop** [comment]
Yes, the goal of this library _is_ to run multiple times a second. If you don't want to run multiple times a second please use `useEffect()` or some other way. You could also conditionally use the component that includes `useAnimationFrame` `<div>{update ? <AnimatedIcon /> : null}</div>`.
