### ISSUE TITLE
an example for start and stop animation at current frame

### ISSUE THREAD

**Issue by khanzzirfan** [franciscop/use-animation-frame#6]
Hi, wonder if you could provide an example start and stop frames and restart from previous stopped frame.

**Comment by franciscop** [comment]
Thanks for opening an Issue. The issues tab in Github are reserved for reporting issues/bugs about the library, not as a general support forum, even if your inquiry involves this repo/library.

[Javascript in Reddit](https://www.reddit.com/r/javascript/) might be useful for general support. If you have some specific issue after trying different things, [StackOverflow](https://stackoverflow.com/) is probably the place to go. I can also provide support, [see my rates and availability](https://superpeer.com/francisco/-/javascript-and-react-help).
